// Generated by ReScript, PLEASE EDIT WITH CARE


function make(id, label, icon, url, items, expanded, disabled, visible, target, separator, className, template, data, command) {
  return {
          id: id,
          label: label,
          icon: icon,
          url: url,
          items: items,
          expanded: expanded,
          disabled: disabled,
          visible: visible,
          target: target,
          separator: separator,
          className: className,
          template: template,
          data: data,
          command: command
        };
}

export {
  make ,
}
/* No side effect */
